# \/\/\/\/\/\/\/ ItemJoin's Configuration Settings, by RockinChaos  \/\/\/\/\/\/\/
# See the tutorial page for a more in-depth explaination; https://www.spigotmc.org/wiki/itemjoin/
config-Version: 7

# English is currently the only support language at the moment!
Language: 'English'

# These are typically general maitenance settings that do not effect much.
General:
  CheckforUpdates: true
  Log-Coloration: true
  Log-Commands: true
  Debugging-Mode: false

# These settings will take effect globally throughout the plugins system.
Settings:
  HeldItem-Slot: DISABLED
  NewNBT-System: true

# These permissions if enabled, determine whether the permission(s) is/are applied to certain players.
Permissions:
  Recieve-Items: false
  Recieve-Items-OP: false
  Commands-OP: false
  Commands-Get: false
  Inventory-Bypass: false

# If enabled these will clear items from their inventory upon performing the specified action.
Clear-Items:
  Option: ItemJoin     # The available option(s) are ALL for all items or ItemJoin for only the ItemJoin items.
  Join: DISABLED
  World-Switch: DISABLED
  Bypass: CREATIVE, OP

# These permissions if enabled, determine whether the permission(s) applies to certain players.
Global-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  triggers: JOIN
  enabled-worlds: DISABLED

# This determines if the action is allowed for all items in the specified worlds.
Prevent-Actions:
  Pickups: DISABLED
  Inventory-Modify: DISABLED

# These are optional dependencies, only enable these if you are wanting to use them.
Dependencies:
  Vault: false
  PlaceholderAPI: false
  Multiverse-Core: false
  Multiverse-Inventories: false
  PerWorldInventory: false
  PerWorldPlugins: false
  xInventories: false
  TokenEnchant: false
  HeadDatabase: false
  WorldGuard: false
  BetterNick: false
  MyWorlds: false
  AuthMe: false