name: ItemJoin
main: me.RockinChaos.itemjoin.ItemJoin
author: RockinChaos
api-version: 1.13
version: 4.9.1-SNAPSHOT
description: Get custom items on join.
website: https://www.spigotmc.org/resources/itemjoin.12661/
softdepend: [Vault, Multiverse, Multiverse-Inventories, xInventories, PlaceholderAPI, PerWorldPlugins, PerWorldInventory, AuthMe, MyWorlds, TokenEnchant, WorldGuard]

commands:
   itemjoin:
      description: Displays a menu giving credit to the creator and the help menu command.
      permission: itemjoin.use
      usage: |
          /itemjoin
   itemjoin help:
      description: Displays the first page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help
   itemjoin help 2:
      description: Displays the second page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 2
   itemjoin help 3:
      description: Displays the third page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 3
   itemjoin help 4:
      description: Displays the fourth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 4
   itemjoin help 5:
      description: Displays the fifth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 5
   itemjoin help 6:
      description: Displays the sixth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 6
   itemjoin help 7:
      description: Displays the seventh page of the available help menu.
      permission: itemjoin.use
      usage: |
          /itemjoin help 7
   itemjoin reload:
      description: Reloads all ItemJoins configuration files and caches any new data.
      permission: itemjoin.reload
      usage: |
          /itemjoin reload
   itemjoin info:
      description: Displays necessary held items information, such as material type.
      permission: itemjoin.use
      usage: |
          /itemjoin info
   itemjoin updates:
      description: Checks for updates that are available for the plugin.
      permission: itemjoin.updates
      usage: |
          /itemjoin updates
   itemjoin permissions:
      description: Checks what permissions you have for ItemJoin.
      permission: itemjoin.permissions
      usage: |
          /itemjoin permissions
   itemjoin permissions 2:
      description: Second page of checking what permissions you have for ItemJoin.
      permission: itemjoin.permissions
      usage: |
          /itemjoin permissions 2
   itemjoin save <item>:
      description: Saves the specified item to the items.yml.
      permission: itemjoin.save
      usage: |
          /itemjoin save <item>
          Example: /itemjoin save special-item - You have saved the item [special-item] to the items.yml.
   itemjoin get <item>:
      description: Gives you the item you specified.
      permission: itemjoin.get
      usage: |
          /itemjoin get <item>
          Example: /itemjoin get Ultra - You have received the item [Ultra]!
   itemjoin get <item> <player>:
      description: Gives you the item you specified to the player.
      permission: itemjoin.get.others
      usage: |
          /itemjoin get <item> <player>
          Example: /itemjoin get Ultra RockinChaos - You have given the item [Ultra] to RockinChaos!
   itemjoin remove <item>:
      description: Removes the item you specified from your inventory.
      permission: itemjoin.remove
      usage: |
          /itemjoin remove <item>
          Example: /itemjoin remove Ultra - You have removed the item [Ultra] from your inventory!
   itemjoin remove <item> <player>:
      description: Removes the item you specified to the player.
      permission: itemjoin.remove.others
      usage: |
          /itemjoin remove <item> <player>
          Example: /itemjoin remove Ultra RockinChaos - You have removed the item [Ultra] to RockinChaos!
   itemjoin enable:
      description: Enables the use of ItemJoin for all players globally.
      permission: itemjoin.enable
      usage: |
          /itemjoin enable
          Example: /itemjoin enable - You have globally enabled ItemJoin.
   itemjoin enable <player>:
      description: Enables the use of ItemJoin for the specified player.
      permission: itemjoin.enable.others
      usage: |
          /itemjoin enable <player>
          Example: /itemjoin enable RockinChaos - You have enabled ItemJoin for RockinChaos!
   itemjoin disable:
      description: Disables the use of ItemJoin for all players globally.
      permission: itemjoin.disable
      usage: |
          /itemjoin disable
          Example: /itemjoin disable - You have globally disabled ItemJoin.
   itemjoin disable <player>:
      description: Disables the use of ItemJoin for the specified player.
      permission: itemjoin.disable.others
      usage: |
          /itemjoin disable <player>
          Example: /itemjoin disable RockinChaos - You have disabled ItemJoin for RockinChaos!
   itemjoin getall:
      description: Gives you all ItemJoin items.
      permission: itemjoin.get
      usage: |
          /itemjoin getall
           Example: /itemjoin getall - You have received all of the ItemJoin items.
   itemjoin getall <player>:
      description: Gives the player all ItemJoin items.
      permission: itemjoin.get.others
      usage: |
          /itemjoin getall <player>
          Example: /itemjoin getall RockinChaos - You have given RockinChaos all of the ItemJoin items that are available.
   itemjoin removeall:
      description: Removes all ItemJoin items from your inventory.
      permission: itemjoin.remove
      usage: |
          /itemjoin removeall
          Example: /itemjoin removeall - You have removed all of the ItemJoin items from your inventory.
   itemjoin removeall <player>:
      description: Removes all ItemJoin items from the players inventory.
      permission: itemjoin.remove.others
      usage: |
          /itemjoin removeall <player>
          Example: /itemjoin removeall RockinChaos - You have removed all of the ItemJoin items from RockinChaos.
   itemjoin world:
      description: Checks what world you are in, useful for debugging purposes.
      permission: itemjoin.use
      usage: |
          /itemjoin world
   itemjoin list:
      description: Checks what items you can get in each available world.
      permission: itemjoin.list
      usage: |
          /itemjoin list
   itemjoin autoupdate:
      description: Force updates ItemJoin, will require a server restart.
      permission: itemjoin.autoupdate
      usage: |
          /itemjoin autoupdate
   itemjoin purge:
      description: This will purge all data from the database file, removing all first-join players, ip-limited players, enabled/disabled players, and all other player data.
      permission: itemjoin.purge
      usage: |
          /itemjoin purge
   itemjoin purge first-join <player>:
      description: This will purge all first-join data for said player from the database file.
      permission: itemjoin.purge
      usage: |
          /itemjoin purge first-join <player>
   itemjoin purge ip-limits <player>:
      description: This will purge all ip-limits data for said player from the database file.
      permission: itemjoin.purge
      usage: |
          /itemjoin purge ip-limits <player>
   ij:
      description: Displays a menu giving credit to the creator and the help menu command.
      permission: itemjoin.use
      usage: |
          /ij
   ij help:
      description: Displays the first page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help
   ij help 2:
      description: Displays the second page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 2
   ij help 3:
      description: Displays the third page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 3
   ij help 4:
      description: Displays the fourth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 4
   ij help 5:
      description: Displays the fifth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 5
   ij help 6:
      description: Displays the sixth page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 6
   ij help 7:
      description: Displays the seventh page of the available help menu.
      permission: itemjoin.use
      usage: |
          /ij help 7
   ij reload:
      description: Reloads all ItemJoins configuration files and caches any new data.
      permission: itemjoin.reload
      usage: |
          /ij reload
   ij info:
      description: Displays necessary held items information, such as material type.
      permission: itemjoin.use
      usage: |
          /ij info
   ij updates:
      description: Checks for updates that are available for the plugin.
      permission: itemjoin.updates
      usage: |
          /ij updates
   ij permissions:
      description: Checks what permissions you have for ItemJoin.
      permission: itemjoin.permissions
      usage: |
          /ij permissions
   ij permissions 2:
      description: Second page of checking what permissions you have for ItemJoin.
      permission: itemjoin.permissions
      usage: |
          /ij permissions 2
   ij save <item>:
      description: Saves the specified item to the items.yml.
      permission: itemjoin.save
      usage: |
          /ij save <item>
          Example: /ij save special-item - You have saved the item [special-item] to the items.yml.
   ij get <item>:
      description: Gives you the item you specified.
      permission: itemjoin.get
      usage: |
          /ij get <item>
          Example: /ij get Ultra - You have received the item [Ultra]!
   ij get <item> <player>:
      description: Gives you the item you specified to the player.
      permission: itemjoin.get.others
      usage: |
          /ij get <item> <player>
          Example: /ij get Ultra RockinChaos - You have given the item [Ultra] to RockinChaos!
   ij remove <item>:
      description: Removes the item you specified from your inventory.
      permission: itemjoin.remove
      usage: |
          /ij remove <item>
          Example: /ij remove Ultra - You have removed the item [Ultra] from your inventory!
   ij remove <item> <player>:
      description: Removes the item you specified to the player.
      permission: itemjoin.remove.others
      usage: |
          /ij remove <item> <player>
          Example: /ij remove Ultra RockinChaos - You have removed the item [Ultra] to RockinChaos!
   ij enable:
      description: Enables the use of ItemJoin for all players globally.
      permission: itemjoin.enable
      usage: |
          /ij enable
          Example: /ij enable - You have globally enabled ItemJoin.
   ij enable <player>:
      description: Enables the use of ItemJoin for the specified player.
      permission: itemjoin.enable.others
      usage: |
          /ij enable <player>
          Example: /ij enable RockinChaos - You have enabled ItemJoin for RockinChaos!
   ij disable:
      description: Disables the use of ItemJoin for all players globally.
      permission: itemjoin.disable
      usage: |
          /ij disable
          Example: /ij disable - You have globally disabled ItemJoin.
   ij disable <player>:
      description: Disables the use of ItemJoin for the specified player.
      permission: itemjoin.disable.others
      usage: |
          /ij disable <player>
          Example: /ij disable RockinChaos - You have disabled ItemJoin for RockinChaos!
   ij getall:
      description: Gives you all ItemJoin items.
      permission: itemjoin.get
      usage: |
          /ij getall
           Example: /ij getall - You have received all of the ItemJoin items.
   ij getall <player>:
      description: Gives the player all ItemJoin items.
      permission: itemjoin.get.others
      usage: |
          /ij getall <player>
          Example: /ij getall RockinChaos - You+ have given RockinChaos all of the ItemJoin items that are available.
   ij removeall:
      description: Removes all ItemJoin items from your inventory.
      permission: itemjoin.remove
      usage: |
          /ij removeall
          Example: /ij removeall - You have removed all of the ItemJoin items from your inventory.
   ij removeall <player>:
      description: Removes all ItemJoin items from the players inventory.
      permission: itemjoin.remove.others
      usage: |
          /ij removeall <player>
          Example: /ij removeall RockinChaos - You have removed all of the ItemJoin items from RockinChaos.
   ij world:
      description: Checks what world you are in, useful for debugging purposes.
      permission: itemjoin.use
      usage: |
          /ij world
   ij list:
      description: Checks what items you can get in each available world.
      permission: itemjoin.list
      usage: |
          /ij list
   ij autoupdate:
      description: Force updates ItemJoin, will require a server restart.
      permission: itemjoin.autoupdate
      usage: |
          /ij autoupdate
   ij purge:
      description: This will purge all data from the database file, removing all first-join players, ip-limited players, enabled/disabled players, and all other player data.
      permission: itemjoin.purge
      usage: |
          /ij purge
   ij purge first-join <player>:
      description: This will purge all first-join data for said player from the database file.
      permission: itemjoin.purge
      usage: |
          /ij purge first-join <player>
   ij purge ip-limits <player>:
      description: This will purge all ip-limits data for said player from the database file.
      permission: itemjoin.purge
      usage: |
          /ij purge ip-limits <player>
          
permissions:
   itemjoin.*:
      description: Allows use of all commands.
      default: false
      children:
          itemjoin.all: true
   itemjoin.all:
      description: Allows use of all commands.
      default: false
      children:
          itemjoin.permissions: true
          itemjoin.use: true
          itemjoin.reload: true
          itemjoin.updates: true
          itemjoin.autoupdate: true
          itemjoin.purge: true
          itemjoin.save: true
          itemjoin.get: true
          itemjoin.get.others: true
          itemjoin.remove: true
          itemjoin.remove.others: true
          itemjoin.enable: true
          itemjoin.enable.others: true
          itemjoin.disable: true
          itemjoin.disable.others: true
          itemjoin.list: true
          itemjoin.bypass.inventorymodify: false
   itemjoin.permissions:
      description: Use of the /itemjoin permissions commands.
      default: true
   itemjoin.use:
      description: Currently allows use of basic commands.
      default: true
   itemjoin.reload:
      description: Allows use of reload command.
      default: false
   itemjoin.updates:
      description: Use of the /itemjoin updates command.
      default: false
   itemjoin.autoupdate:
      description: Use of the /itemjoin autoupdate command.
      default: false
   itemjoin.purge:
      description: Use of the /itemjoin purge command.
      default: false
   itemjoin.save:
      description: Use of the /itemjoin save <item> command.
      default: false
   itemjoin.get:
      description: Use of the /itemjoin get <item> command.
      default: false
   itemjoin.get.others:
      description: Use of the /itemjoin get <item> <player> for player command.
      default: false
   itemjoin.remove:
      description: Use of the /itemjoin remove <item> command.
      default: false
   itemjoin.remove.others:
      description: Use of the /itemjoin remove <item> <player> for player command.
      default: false
   itemjoin.enable:
      description: Use of the /itemjoin enable global command.
      default: false
   itemjoin.enable.others:
      description: Use of the /itemjoin enable <player> for player command.
      default: false
   itemjoin.disable:
      description: Use of the /itemjoin disable global command.
      default: false
   itemjoin.disable.others:
      description: Use of the /itemjoin disable <player> for player command.
      default: false
   itemjoin.list:
      description: Use of the /itemjoin list command.
      default: false
   itemjoin.bypass.inventorymodify:
      description: Players will this permission will bypass any effect that the inventory modify flag has.
      default: false